//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webLoyal.Resources.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webLoyal.Resources.language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accident Rate.
        /// </summary>
        public static string AccidentRate {
            get {
                return ResourceManager.GetString("AccidentRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string AccountType {
            get {
                return ResourceManager.GetString("AccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string Achievements {
            get {
                return ResourceManager.GetString("Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Certificates.
        /// </summary>
        public static string ActiveCertificates {
            get {
                return ResourceManager.GetString("ActiveCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Cost.
        /// </summary>
        public static string AdministrativeCost {
            get {
                return ResourceManager.GetString("AdministrativeCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Code.
        /// </summary>
        public static string AgencyCode {
            get {
                return ResourceManager.GetString("AgencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Name.
        /// </summary>
        public static string AgencyName {
            get {
                return ResourceManager.GetString("AgencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent App.
        /// </summary>
        public static string AgentApp {
            get {
                return ResourceManager.GetString("AgentApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Code.
        /// </summary>
        public static string AgentCode {
            get {
                return ResourceManager.GetString("AgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Portal.
        /// </summary>
        public static string AgentPortal {
            get {
                return ResourceManager.GetString("AgentPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents.
        /// </summary>
        public static string Agents {
            get {
                return ResourceManager.GetString("Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents List.
        /// </summary>
        public static string AgentsList {
            get {
                return ResourceManager.GetString("AgentsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Payment Form.
        /// </summary>
        public static string AnnualPaymentMethod {
            get {
                return ResourceManager.GetString("AnnualPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending Doctor.
        /// </summary>
        public static string AttendingDoctor {
            get {
                return ResourceManager.GetString("AttendingDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Payment.
        /// </summary>
        public static string AutomaticPayment {
            get {
                return ResourceManager.GetString("AutomaticPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Home.
        /// </summary>
        public static string BackHome {
            get {
                return ResourceManager.GetString("BackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Data.
        /// </summary>
        public static string BankData {
            get {
                return ResourceManager.GetString("BankData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banking Address.
        /// </summary>
        public static string BankingAddress {
            get {
                return ResourceManager.GetString("BankingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Birthdate {
            get {
                return ResourceManager.GetString("Birthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        public static string Bonus {
            get {
                return ResourceManager.GetString("Bonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaigns.
        /// </summary>
        public static string Campaigns {
            get {
                return ResourceManager.GetString("Campaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Certificates.
        /// </summary>
        public static string CanceledCertificates {
            get {
                return ResourceManager.GetString("CanceledCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of Denial.
        /// </summary>
        public static string CauseOfDenial {
            get {
                return ResourceManager.GetString("CauseOfDenial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Code.
        /// </summary>
        public static string CertificateCode {
            get {
                return ResourceManager.GetString("CertificateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate History.
        /// </summary>
        public static string CertificateHistory {
            get {
                return ResourceManager.GetString("CertificateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates In Grace Period.
        /// </summary>
        public static string CertificatesInGracePeriod {
            get {
                return ResourceManager.GetString("CertificatesInGracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates Pending Renewal.
        /// </summary>
        public static string CertificatesPendingRenewal {
            get {
                return ResourceManager.GetString("CertificatesPendingRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificateStateCode.
        /// </summary>
        public static string CertificateStateCode {
            get {
                return ResourceManager.GetString("CertificateStateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Status Date.
        /// </summary>
        public static string CivilStatus {
            get {
                return ResourceManager.GetString("CivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClaimDate.
        /// </summary>
        public static string ClaimDate {
            get {
                return ResourceManager.GetString("ClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Id.
        /// </summary>
        public static string ClaimId {
            get {
                return ResourceManager.GetString("ClaimId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Info.
        /// </summary>
        public static string ClaimInfo {
            get {
                return ResourceManager.GetString("ClaimInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims History.
        /// </summary>
        public static string ClaimsHistory {
            get {
                return ResourceManager.GetString("ClaimsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Report Format.
        /// </summary>
        public static string ClaimsReportFormat {
            get {
                return ResourceManager.GetString("ClaimsReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Reports Id.
        /// </summary>
        public static string ClaimsReportsId {
            get {
                return ResourceManager.GetString("ClaimsReportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value.
        /// </summary>
        public static string ClaimValue {
            get {
                return ResourceManager.GetString("ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Files.
        /// </summary>
        public static string CloudFiles {
            get {
                return ResourceManager.GetString("CloudFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Agent Sale.
        /// </summary>
        public static string CodeAgentSale {
            get {
                return ResourceManager.GetString("CodeAgentSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeMGA..
        /// </summary>
        public static string CodeMGA {
            get {
                return ResourceManager.GetString("CodeMGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code State Quota.
        /// </summary>
        public static string CodeStateQuota {
            get {
                return ResourceManager.GetString("CodeStateQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type Sale.
        /// </summary>
        public static string CodeTypeSale {
            get {
                return ResourceManager.GetString("CodeTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commissionable Premium.
        /// </summary>
        public static string CommissionablePremium {
            get {
                return ResourceManager.GetString("CommissionablePremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name of the Provider.
        /// </summary>
        public static string CompanyNameOfTheProvider {
            get {
                return ResourceManager.GetString("CompanyNameOfTheProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional Coverage Section.
        /// </summary>
        public static string ConditionalCoverageSection {
            get {
                return ResourceManager.GetString("ConditionalCoverageSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Date.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to.
        /// </summary>
        public static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Description.
        /// </summary>
        public static string CountryDescription {
            get {
                return ResourceManager.GetString("CountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Certificate.
        /// </summary>
        public static string CreateCertificate {
            get {
                return ResourceManager.GetString("CreateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Campaign.
        /// </summary>
        public static string CreateNewCampaign {
            get {
                return ResourceManager.GetString("CreateNewCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Provider.
        /// </summary>
        public static string CreateProvider {
            get {
                return ResourceManager.GetString("CreateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTP.
        /// </summary>
        public static string CTP {
            get {
                return ResourceManager.GetString("CTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Concepts.
        /// </summary>
        public static string DashboardConcepts {
            get {
                return ResourceManager.GetString("DashboardConcepts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Collection.
        /// </summary>
        public static string DateCollection {
            get {
                return ResourceManager.GetString("DateCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Effectiveness.
        /// </summary>
        public static string DateEffectiveness {
            get {
                return ResourceManager.GetString("DateEffectiveness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Admission.
        /// </summary>
        public static string DateOfAdmission {
            get {
                return ResourceManager.GetString("DateOfAdmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Applies.
        /// </summary>
        public static string DeductibleApplies {
            get {
                return ResourceManager.GetString("DeductibleApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductibles Text.
        /// </summary>
        public static string DeductiblesText {
            get {
                return ResourceManager.GetString("DeductiblesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Files.
        /// </summary>
        public static string DeletedFiles {
            get {
                return ResourceManager.GetString("DeletedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Country.
        /// </summary>
        public static string DescriptionCountry {
            get {
                return ResourceManager.GetString("DescriptionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description FormPayment.
        /// </summary>
        public static string DescriptionFormPayment {
            get {
                return ResourceManager.GetString("DescriptionFormPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Policy.
        /// </summary>
        public static string DescriptionPolicy {
            get {
                return ResourceManager.GetString("DescriptionPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Provider Status.
        /// </summary>
        public static string DescriptionProviderStatus {
            get {
                return ResourceManager.GetString("DescriptionProviderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Reason Cancellation.
        /// </summary>
        public static string DescriptionReasonCancellation {
            get {
                return ResourceManager.GetString("DescriptionReasonCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description State Certificate.
        /// </summary>
        public static string DescriptionStateCertificate {
            get {
                return ResourceManager.GetString("DescriptionStateCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Type Sale.
        /// </summary>
        public static string DescriptionTypeSale {
            get {
                return ResourceManager.GetString("DescriptionTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Date.
        /// </summary>
        public static string DischargeDate {
            get {
                return ResourceManager.GetString("DischargeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocumentName {
            get {
                return ResourceManager.GetString("DocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Type.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Downloads {
            get {
                return ResourceManager.GetString("Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dx.
        /// </summary>
        public static string Dx {
            get {
                return ResourceManager.GetString("Dx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective End Date.
        /// </summary>
        public static string EffectiveEndDate {
            get {
                return ResourceManager.GetString("EffectiveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Start Date.
        /// </summary>
        public static string EffectiveStartDate {
            get {
                return ResourceManager.GetString("EffectiveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your mobile device..
        /// </summary>
        public static string EnterTheCodeSentToYourMobileDevice {
            get {
                return ResourceManager.GetString("EnterTheCodeSentToYourMobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter User.
        /// </summary>
        public static string EnterUser {
            get {
                return ResourceManager.GetString("EnterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        public static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string FinishDate {
            get {
                return ResourceManager.GetString("FinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string Folders {
            get {
                return ResourceManager.GetString("Folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string ForbiddenMsj {
            get {
                return ResourceManager.GetString("ForbiddenMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps. Something is broken. We’ve been automatically alerted of the issue and will work to fix it asap..
        /// </summary>
        public static string ForbiddenOoppsMsj {
            get {
                return ResourceManager.GetString("ForbiddenOoppsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Denial Letter.
        /// </summary>
        public static string GenerateDenialLetter {
            get {
                return ResourceManager.GetString("GenerateDenialLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get 2TB (2,000GB) of storage now and get 40% off. Offers ends soon.
        /// </summary>
        public static string Get2TBOfStorageNowAndGet40OffOffersEndsSoon {
            get {
                return ResourceManager.GetString("Get2TBOfStorageNowAndGet40OffOffersEndsSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Or Provider.
        /// </summary>
        public static string HospitalOrProvider {
            get {
                return ResourceManager.GetString("HospitalOrProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC10.
        /// </summary>
        public static string IC10 {
            get {
                return ResourceManager.GetString("IC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Construction.
        /// </summary>
        public static string InConstructionMsj {
            get {
                return ResourceManager.GetString("InConstructionMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This website is under construction. To offer the best experience to our users we are working on the development of our platform..
        /// </summary>
        public static string InConstructionOoppsMsj {
            get {
                return ResourceManager.GetString("InConstructionOoppsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Of The Affected Of The Policy.
        /// </summary>
        public static string InformationOfTheAffectedOfThePolicy {
            get {
                return ResourceManager.GetString("InformationOfTheAffectedOfThePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured.
        /// </summary>
        public static string Insured {
            get {
                return ResourceManager.GetString("Insured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Name.
        /// </summary>
        public static string InsuredName {
            get {
                return ResourceManager.GetString("InsuredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured Persons.
        /// </summary>
        public static string InsuredPersons {
            get {
                return ResourceManager.GetString("InsuredPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string InternalServerErrorMsj {
            get {
                return ResourceManager.GetString("InternalServerErrorMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps. The server encountered an internal server error and was unable to complete your request. Please try again later..
        /// </summary>
        public static string InternalServerErrorOoppsMsj {
            get {
                return ResourceManager.GetString("InternalServerErrorOoppsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Update Process.
        /// </summary>
        public static string InUpdateProcess {
            get {
                return ResourceManager.GetString("InUpdateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your mobile device..
        /// </summary>
        public static string Isvalidmsj {
            get {
                return ResourceManager.GetString("Isvalidmsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jhon@smith.com.
        /// </summary>
        public static string Jhon_smith_com {
            get {
                return ResourceManager.GetString("Jhon@smith.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access.
        /// </summary>
        public static string LastAccess {
            get {
                return ResourceManager.GetString("LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Of Guarantee.
        /// </summary>
        public static string LetterOfGuarantee {
            get {
                return ResourceManager.GetString("LetterOfGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log User.
        /// </summary>
        public static string LogUser {
            get {
                return ResourceManager.GetString("LogUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Symptoms.
        /// </summary>
        public static string MainSymptoms {
            get {
                return ResourceManager.GetString("MainSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as Important.
        /// </summary>
        public static string MarkAsImportant {
            get {
                return ResourceManager.GetString("MarkAsImportant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Speciality.
        /// </summary>
        public static string MedicalSpeciality {
            get {
                return ResourceManager.GetString("MedicalSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Payment Method.
        /// </summary>
        public static string MonthlyPaymentMethod {
            get {
                return ResourceManager.GetString("MonthlyPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        public static string MoveTo {
            get {
                return ResourceManager.GetString("MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Devices.
        /// </summary>
        public static string MyDevices {
            get {
                return ResourceManager.GetString("MyDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Agent Sale.
        /// </summary>
        public static string NameAgentSale {
            get {
                return ResourceManager.GetString("NameAgentSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Beneficiary.
        /// </summary>
        public static string NameOfBeneficiary {
            get {
                return ResourceManager.GetString("NameOfBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name SubAgent.
        /// </summary>
        public static string NameSubAgent {
            get {
                return ResourceManager.GetString("NameSubAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Claim.
        /// </summary>
        public static string NewClaim {
            get {
                return ResourceManager.GetString("NewClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes History.
        /// </summary>
        public static string NotesHistory {
            get {
                return ResourceManager.GetString("NotesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFoundMsj {
            get {
                return ResourceManager.GetString("NotFoundMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps. The page you were looking for doesn&apos;t exist. You may have mistyped the address or the page may have moved..
        /// </summary>
        public static string NotFoundOoppsMsj {
            get {
                return ResourceManager.GetString("NotFoundOoppsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Insurance.
        /// </summary>
        public static string NotifyInsuranceAgent {
            get {
                return ResourceManager.GetString("NotifyInsuranceAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Insured.
        /// </summary>
        public static string NotifyInsured {
            get {
                return ResourceManager.GetString("NotifyInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Provider.
        /// </summary>
        public static string NotifyProvider {
            get {
                return ResourceManager.GetString("NotifyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Insured.
        /// </summary>
        public static string NumberInsured {
            get {
                return ResourceManager.GetString("NumberInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Of The Claim.
        /// </summary>
        public static string OriginOfTheClaim {
            get {
                return ResourceManager.GetString("OriginOfTheClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Code.
        /// </summary>
        public static string OwnerCode {
            get {
                return ResourceManager.GetString("OwnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OwnerName.
        /// </summary>
        public static string OwnerName {
            get {
                return ResourceManager.GetString("OwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password One.
        /// </summary>
        public static string PasswordOne {
            get {
                return ResourceManager.GetString("PasswordOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Two.
        /// </summary>
        public static string PasswordTwo {
            get {
                return ResourceManager.GetString("PasswordTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Day.
        /// </summary>
        public static string PayDay {
            get {
                return ResourceManager.GetString("PayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People Served.
        /// </summary>
        public static string PeopleServed {
            get {
                return ResourceManager.GetString("PeopleServed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Rating.
        /// </summary>
        public static string PerformanceRating {
            get {
                return ResourceManager.GetString("PerformanceRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Stuff.
        /// </summary>
        public static string PersonalStuff {
            get {
                return ResourceManager.GetString("PersonalStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code.
        /// </summary>
        public static string PlanCode {
            get {
                return ResourceManager.GetString("PlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code.
        /// </summary>
        public static string PolicyCode {
            get {
                return ResourceManager.GetString("PolicyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Dependent.
        /// </summary>
        public static string PolicyDependent {
            get {
                return ResourceManager.GetString("PolicyDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Group.
        /// </summary>
        public static string PolicyGroup {
            get {
                return ResourceManager.GetString("PolicyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policyholder Data.
        /// </summary>
        public static string PolicyholderData {
            get {
                return ResourceManager.GetString("PolicyholderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policyholder Details.
        /// </summary>
        public static string PolicyholderDetails {
            get {
                return ResourceManager.GetString("PolicyholderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder Information.
        /// </summary>
        public static string PolicyHolderInformation {
            get {
                return ResourceManager.GetString("PolicyHolderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premiums.
        /// </summary>
        public static string Premiums {
            get {
                return ResourceManager.GetString("Premiums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Claims.
        /// </summary>
        public static string PreviousClaims {
            get {
                return ResourceManager.GetString("PreviousClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Code.
        /// </summary>
        public static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarterly Payment Method.
        /// </summary>
        public static string QuarterlyPaymentMethod {
            get {
                return ResourceManager.GetString("QuarterlyPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quota Value.
        /// </summary>
        public static string QuotaValue {
            get {
                return ResourceManager.GetString("QuotaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Accessed Files.
        /// </summary>
        public static string RecentlyAccessedFiles {
            get {
                return ResourceManager.GetString("RecentlyAccessedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recents.
        /// </summary>
        public static string Recents {
            get {
                return ResourceManager.GetString("Recents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognitions.
        /// </summary>
        public static string Recognitions {
            get {
                return ResourceManager.GetString("Recognitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Recordings {
            get {
                return ResourceManager.GetString("Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us your email address, to identify your identity..
        /// </summary>
        public static string Recovermsj {
            get {
                return ResourceManager.GetString("Recovermsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your mobile device..
        /// </summary>
        public static string RecoverSmsMsj {
            get {
                return ResourceManager.GetString("RecoverSmsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Claim Date.
        /// </summary>
        public static string ReportClaimDate {
            get {
                return ResourceManager.GetString("ReportClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representation.
        /// </summary>
        public static string Representation {
            get {
                return ResourceManager.GetString("Representation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Code.
        /// </summary>
        public static string RequestCode {
            get {
                return ResourceManager.GetString("RequestCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing Code.
        /// </summary>
        public static string RoutingCode {
            get {
                return ResourceManager.GetString("RoutingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semiannual Payment Form.
        /// </summary>
        public static string SemiannualPaymentMethod {
            get {
                return ResourceManager.GetString("SemiannualPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        public static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Unavailable.
        /// </summary>
        public static string ServicesUnavailableMsj {
            get {
                return ResourceManager.GetString("ServicesUnavailableMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oopps. The server is unable to service your request due to maintenance downtime or capacity problems. Please try again later..
        /// </summary>
        public static string ServicesUnavailableOoppsMsj {
            get {
                return ResourceManager.GetString("ServicesUnavailableOoppsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Description.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Status.
        /// </summary>
        public static string StorageStatus {
            get {
                return ResourceManager.GetString("StorageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubAgent Code.
        /// </summary>
        public static string SubAgentCode {
            get {
                return ResourceManager.GetString("SubAgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom Date.
        /// </summary>
        public static string SymptomDate {
            get {
                return ResourceManager.GetString("SymptomDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms.
        /// </summary>
        public static string Symptoms {
            get {
                return ResourceManager.GetString("Symptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomodar App.
        /// </summary>
        public static string TomodarApp {
            get {
                return ResourceManager.GetString("TomodarApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Agents.
        /// </summary>
        public static string TopAgents {
            get {
                return ResourceManager.GetString("TopAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Register.
        /// </summary>
        public static string ToRegister {
            get {
                return ResourceManager.GetString("ToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Objects.
        /// </summary>
        public static string TriDObjects {
            get {
                return ResourceManager.GetString("TriDObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Document.
        /// </summary>
        public static string TypeOfDocument {
            get {
                return ResourceManager.GetString("TypeOfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Data.
        /// </summary>
        public static string UpdateData {
            get {
                return ResourceManager.GetString("UpdateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Found.
        /// </summary>
        public static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we were unable to validate your credentials.
        /// </summary>
        public static string UserNotFoundMsj {
            get {
                return ResourceManager.GetString("UserNotFoundMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Interest.
        /// </summary>
        public static string ValueInterest {
            get {
                return ResourceManager.GetString("ValueInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string ViewDetails {
            get {
                return ResourceManager.GetString("ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a moment....
        /// </summary>
        public static string WaitMoment {
            get {
                return ResourceManager.GetString("WaitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experience.
        /// </summary>
        public static string WorkExperience {
            get {
                return ResourceManager.GetString("WorkExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Files.
        /// </summary>
        public static string ZipFiles {
            get {
                return ResourceManager.GetString("ZipFiles", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Generate Guarantee Letter.
        /// </summary>
        public static string GenerateGuaranteeLetter {
            get {
                return ResourceManager.GetString("GenerateGuaranteeLetter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Budget Number.
        /// </summary>
        public static string BudgetNumber {
            get {
                return ResourceManager.GetString("BudgetNumber", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Admissions Department.
        /// </summary>
        public static string AdmissionsDepartment {
            get {
                return ResourceManager.GetString("AdmissionsDepartment", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Deductible Amount.
        /// </summary>
        public static string DeductibleAmount {
            get {
                return ResourceManager.GetString("DeductibleAmount", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to USD Insured Liability.
        /// </summary>
        public static string USDInsuredLiability {
            get {
                return ResourceManager.GetString("USDInsuredLiability", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to NOTICE OF CONFIDENTIALITY.
        /// </summary>
        public static string NOTICEOFCONFIDENTIALITY {
            get {
                return ResourceManager.GetString("NOTICEOFCONFIDENTIALITY", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Generate Letter Of Guarantee.
        /// </summary>
        public static string GenerateLetterOfGuarantee {
            get {
                return ResourceManager.GetString("GenerateLetterOfGuarantee", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Claim Office.
        /// </summary>
        public static string ClaimOffice {
            get {
                return ResourceManager.GetString("ClaimOffice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Generate Letter Of Claim Department.
        /// </summary>
        public static string ClaimDepartment {
            get {
                return ResourceManager.GetString("ClaimDepartment", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Claim Status Description.
        /// </summary>
        public static string ClaimStatusDescription {
            get {
                return ResourceManager.GetString("ClaimStatusDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Description Of The Claim Type.
        /// </summary>
        public static string DescriptionOfTheClaimType {
            get {
                return ResourceManager.GetString("DescriptionOfTheClaimType", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Description Of Origin.
        /// </summary>
        public static string DescriptionOfOrigin {
            get {
                return ResourceManager.GetString("DescriptionOfOrigin", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Claim Description.
        /// </summary>
        public static string ClaimDescription {
            get {
                return ResourceManager.GetString("ClaimDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Deductible Value.
        /// </summary>
        public static string DeductibleValue {
            get {
                return ResourceManager.GetString("DeductibleValue", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Agent History.
        /// </summary>
        public static string AgentHistory {
            get {
                return ResourceManager.GetString("AgentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agents History.
        /// </summary>
        public static string AgentsHistory {
            get {
                return ResourceManager.GetString("AgentsHistory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to New Business Policies.
        /// </summary>
        public static string NewBusinessPolicies {
            get {
                return ResourceManager.GetString("NewBusinessPolicies", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Charged Policies.
        /// </summary>
        public static string ChargedPolicies {
            get {
                return ResourceManager.GetString("ChargedPolicies", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Policies Under Evaluation.
        /// </summary>
        public static string PoliciesUnderEvaluation {
            get {
                return ResourceManager.GetString("PoliciesUnderEvaluation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Approved Policies.
        /// </summary>
        public static string ApprovedPolicies {
            get {
                return ResourceManager.GetString("ApprovedPolicies", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Agents Id.
        /// </summary>
        public static string AgentsId {
            get {
                return ResourceManager.GetString("AgentsId", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Agents Status.
        /// </summary>
        public static string AgentsStatus {
            get {
                return ResourceManager.GetString("AgentsStatus", resourceCulture);
            }
        }
    }
}
