//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webLoyal.Resources.language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webLoyal.Resources.language.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Certificates.
        /// </summary>
        public static string ActiveCertificates {
            get {
                return ResourceManager.GetString("ActiveCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent App.
        /// </summary>
        public static string AgentApp {
            get {
                return ResourceManager.GetString("AgentApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Portal.
        /// </summary>
        public static string AgentPortal {
            get {
                return ResourceManager.GetString("AgentPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attending Doctor.
        /// </summary>
        public static string AttendingDoctor {
            get {
                return ResourceManager.GetString("AttendingDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Name.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled Certificates.
        /// </summary>
        public static string CanceledCertificates {
            get {
                return ResourceManager.GetString("CanceledCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string Certificate {
            get {
                return ResourceManager.GetString("Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Code.
        /// </summary>
        public static string CertificateCode {
            get {
                return ResourceManager.GetString("CertificateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate History.
        /// </summary>
        public static string CertificateHistory {
            get {
                return ResourceManager.GetString("CertificateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates In Grace Period.
        /// </summary>
        public static string CertificatesInGracePeriod {
            get {
                return ResourceManager.GetString("CertificatesInGracePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates Pending Renewal.
        /// </summary>
        public static string CertificatesPendingRenewal {
            get {
                return ResourceManager.GetString("CertificatesPendingRenewal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Id.
        /// </summary>
        public static string ClaimID {
            get {
                return ResourceManager.GetString("ClaimID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Info.
        /// </summary>
        public static string ClaimInfo {
            get {
                return ResourceManager.GetString("ClaimInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims.
        /// </summary>
        public static string Claims {
            get {
                return ResourceManager.GetString("Claims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims History.
        /// </summary>
        public static string ClaimsHistory {
            get {
                return ResourceManager.GetString("ClaimsHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Report Format.
        /// </summary>
        public static string ClaimsReportFormat {
            get {
                return ResourceManager.GetString("ClaimsReportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Reports Id.
        /// </summary>
        public static string ClaimsReportsId {
            get {
                return ResourceManager.GetString("ClaimsReportsId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Value.
        /// </summary>
        public static string ClaimValue {
            get {
                return ResourceManager.GetString("ClaimValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Type Sale.
        /// </summary>
        public static string CodeTypeSale {
            get {
                return ResourceManager.GetString("CodeTypeSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name of the Provider.
        /// </summary>
        public static string CompanyNameOfTheProvider {
            get {
                return ResourceManager.GetString("CompanyNameOfTheProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Description.
        /// </summary>
        public static string CountryDescription {
            get {
                return ResourceManager.GetString("CountryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Provider.
        /// </summary>
        public static string CreateProvider {
            get {
                return ResourceManager.GetString("CreateProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTP.
        /// </summary>
        public static string CTP {
            get {
                return ResourceManager.GetString("CTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductible Applies.
        /// </summary>
        public static string DeductibleApplies {
            get {
                return ResourceManager.GetString("DeductibleApplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripction.
        /// </summary>
        public static string Descripction {
            get {
                return ResourceManager.GetString("Descripction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Country.
        /// </summary>
        public static string DescriptionCountry {
            get {
                return ResourceManager.GetString("DescriptionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Provider Status.
        /// </summary>
        public static string DescriptionProviderStatus {
            get {
                return ResourceManager.GetString("DescriptionProviderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis.
        /// </summary>
        public static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dx.
        /// </summary>
        public static string Dx {
            get {
                return ResourceManager.GetString("Dx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective End Date.
        /// </summary>
        public static string EffectiveEndDate {
            get {
                return ResourceManager.GetString("EffectiveEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Start Date.
        /// </summary>
        public static string EffectiveStartDate {
            get {
                return ResourceManager.GetString("EffectiveStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency.
        /// </summary>
        public static string Emergency {
            get {
                return ResourceManager.GetString("Emergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions.
        /// </summary>
        public static string Exclusions {
            get {
                return ResourceManager.GetString("Exclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Date.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC10.
        /// </summary>
        public static string IC10 {
            get {
                return ResourceManager.GetString("IC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Of The Affected Of The Policy.
        /// </summary>
        public static string InformationOfTheAffectedOfThePolicy {
            get {
                return ResourceManager.GetString("InformationOfTheAffectedOfThePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insured.
        /// </summary>
        public static string Insured {
            get {
                return ResourceManager.GetString("Insured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Update Process.
        /// </summary>
        public static string InUpdateProcess {
            get {
                return ResourceManager.GetString("InUpdateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your mobile device..
        /// </summary>
        public static string Isvalidmsj {
            get {
                return ResourceManager.GetString("Isvalidmsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jhon@smith.com.
        /// </summary>
        public static string Jhon_smith_com {
            get {
                return ResourceManager.GetString("Jhon@smith.com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter Of Guarantee.
        /// </summary>
        public static string LetterOfGuarantee {
            get {
                return ResourceManager.GetString("LetterOfGuarantee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log User.
        /// </summary>
        public static string LogUser {
            get {
                return ResourceManager.GetString("LogUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Symptoms.
        /// </summary>
        public static string MainSymptoms {
            get {
                return ResourceManager.GetString("MainSymptoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Speciality.
        /// </summary>
        public static string MedicalSpeciality {
            get {
                return ResourceManager.GetString("MedicalSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Claim.
        /// </summary>
        public static string NewClaim {
            get {
                return ResourceManager.GetString("NewClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes History.
        /// </summary>
        public static string NotesHistory {
            get {
                return ResourceManager.GetString("NotesHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Insurance.
        /// </summary>
        public static string NotifyInsuranceAgent {
            get {
                return ResourceManager.GetString("NotifyInsuranceAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Insured.
        /// </summary>
        public static string NotifyInsured {
            get {
                return ResourceManager.GetString("NotifyInsured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Provider.
        /// </summary>
        public static string NotifyProvider {
            get {
                return ResourceManager.GetString("NotifyProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin Of The Claim.
        /// </summary>
        public static string OriginOfTheClaim {
            get {
                return ResourceManager.GetString("OriginOfTheClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PassWord {
            get {
                return ResourceManager.GetString("PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Code.
        /// </summary>
        public static string PlanCode {
            get {
                return ResourceManager.GetString("PlanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Code.
        /// </summary>
        public static string PolicyCode {
            get {
                return ResourceManager.GetString("PolicyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Holder Information.
        /// </summary>
        public static string PolicyHolderInformation {
            get {
                return ResourceManager.GetString("PolicyHolderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        public static string PolicyNumber {
            get {
                return ResourceManager.GetString("PolicyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Claims.
        /// </summary>
        public static string PreviousClaims {
            get {
                return ResourceManager.GetString("PreviousClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Code.
        /// </summary>
        public static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Date.
        /// </summary>
        public static string RecordDate {
            get {
                return ResourceManager.GetString("RecordDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recover.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us your email address, to identify your identity..
        /// </summary>
        public static string Recovermsj {
            get {
                return ResourceManager.GetString("Recovermsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the code sent to your mobile device..
        /// </summary>
        public static string RecoverSmsMsj {
            get {
                return ResourceManager.GetString("RecoverSmsMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        public static string Refund {
            get {
                return ResourceManager.GetString("Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Claim Date.
        /// </summary>
        public static string ReportClaimDate {
            get {
                return ResourceManager.GetString("ReportClaimDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Description.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptom Date.
        /// </summary>
        public static string SymptomDate {
            get {
                return ResourceManager.GetString("SymptomDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomodar App.
        /// </summary>
        public static string TomodarApp {
            get {
                return ResourceManager.GetString("TomodarApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Document.
        /// </summary>
        public static string TypeOfDocument {
            get {
                return ResourceManager.GetString("TypeOfDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Found.
        /// </summary>
        public static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we were unable to validate your credentials.
        /// </summary>
        public static string UserNotFoundMsj {
            get {
                return ResourceManager.GetString("UserNotFoundMsj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait a moment....
        /// </summary>
        public static string WaitMoment {
            get {
                return ResourceManager.GetString("WaitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
